"use client";

import { AlertTriangle, Inbox, X } from "lucide-react";

export function Drawer({ title, eyebrow, onClose, children, width = "max-w-2xl" }: { title: string; eyebrow: string; onClose: () => void; children: React.ReactNode; width?: string }) {
  return <div className="fixed inset-0 z-[60]"><button className="absolute inset-0 bg-[#061426]/45" onClick={onClose} aria-label={`Close ${title}`} /><aside role="dialog" aria-modal="true" aria-labelledby="crm-drawer-title" className={`absolute inset-y-0 right-0 flex w-full ${width} flex-col bg-[#f3efe7] shadow-2xl`}><div className="flex items-center justify-between border-b border-[#061426]/10 px-5 py-4"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-[#9a7432]">{eyebrow}</p><h2 id="crm-drawer-title" className="mt-1 text-xl font-black uppercase">{title}</h2></div><button onClick={onClose} aria-label={`Close ${title}`} className="grid size-9 place-items-center"><X className="size-5" /></button></div>{children}</aside></div>;
}

export function LoadingState() { return <div className="grid min-h-72 place-items-center"><div className="loader !border-[#061426]/15 !border-t-[#d6aa55]" /></div>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="grid min-h-72 place-items-center p-8 text-center"><div><Inbox className="mx-auto size-7 text-[#061426]/25" /><h2 className="mt-4 text-sm font-black uppercase">{title}</h2><p className="mt-2 text-sm text-[#061426]/45">{description}</p></div></div>; }
export function PageError({ error, clear }: { error: string; clear: () => void }) { return error ? <div role="alert" className="mb-5 flex items-center justify-between border border-red-300 bg-red-50 p-4 text-sm text-red-800"><span>{error}</span><button onClick={clear} aria-label="Dismiss error"><X className="size-4" /></button></div> : null; }
export function ConfirmDelete({ title, description, error, onCancel, onConfirm }: { title: string; description: string; error: string; onCancel: () => void; onConfirm: () => void }) { return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#061426]/60 p-5"><div role="alertdialog" aria-modal="true" aria-labelledby="delete-title" className="w-full max-w-sm bg-white p-6 shadow-2xl"><AlertTriangle className="size-6 text-red-700" /><h2 id="delete-title" className="mt-4 text-lg font-black uppercase">{title}</h2><p className="mt-2 text-sm leading-6 text-[#061426]/55">{description}</p>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button onClick={onCancel} className="h-10 border border-[#061426]/15 px-4 text-xs font-bold">Cancel</button><button onClick={onConfirm} className="h-10 bg-red-700 px-4 text-xs font-bold text-white">Delete</button></div></div></div>; }
export const inputClass = "h-11 w-full border border-[#061426]/15 bg-white px-3 text-sm outline-none focus:border-[#9a7432]";
export const textareaClass = "w-full border border-[#061426]/15 bg-white p-3 text-sm outline-none focus:border-[#9a7432]";
export function formatMoney(value: number | null) { return value == null ? "Not provided" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
